version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.6.0
      - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    environment:
      - NODE_ENV: development

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run Jest and Send Coverage Reports To Coveralls"
          command: yarn test --coverage --coverageReporters=text-lcov --watchAll=false | ./node_modules/coveralls/bin/coveralls.js
